server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true
    instance-id:  ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
spring:
  application:
    name: eureka-server-demo
