FROM java:8
MAINTAINER spring-consumer eureka 使用 - by huangjunhao
ADD part3-spring-cloud-eureka-consumer-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8089
ENTRYPOINT ["java","-jar","app.jar","--server.port=8089"]
